CREATE TABLE DEALS (INTITULE VARCHAR(50) CONSTRAINT PKDEALS PRIMARY KEY, DESCRIPTION_D VARCHAR(50) CONSTRAINT NNDESCRIPTION NOT NULL, PRIX_I NUMBER, PRIX_D NUMBER, REDUCTION NUMBER CONSTRAINT NNREDUCTION NOT NULL, DATE_D DATE , PERIOD_V NUMBER CONSTRAINT NNPERIOD NOT NULL, NOTED NUMBER CONSTRAINT CHKNOTED CHECK (NOTED<=5 AND NOTED>=0), EXPIRE VARCHAR(3) CONSTRAINT CHKEX CHECK (EXPIRE='OUI' OR EXPIRE='NON'), NOM_CATG VARCHAR(20), NOM_PRESTATAIRE VARCHAR(50));

CREATE TABLE CATEGORIES (NOM_CATG VARCHAR(20) CONSTRAINT PKCATEGORIES PRIMARY KEY, NOM_PRESTATAIRE VARCHAR(50));

CREATE TABLE MEMBRES (LOGIN VARCHAR(15) CONSTRAINT PKMEMBRES PRIMARY KEY, MDP VARCHAR(50), NOM VARCHAR(50) CONSTRAINT NNNOM NOT NULL, PRENOM VARCHAR(50) CONSTRAINT NNPRENOM NOT NULL);
ALTER TABLE MEMBRES ADD CONSTRAINT CHKLOGIN CHECK (LOGIN<>NOM AND LOGIN<>PRENOM);

CREATE TABLE PRESTATAIRES_SERVICES (NOM_PREST VARCHAR(50) CONSTRAINT PKPRESTATAIRES PRIMARY KEY, NUM_ADRESSE NUMBER, RUE_ADRESSE VARCHAR(20), VILLE VARCHAR(20), CP NUMBER, TEL NUMBER CONSTRAINT NNTEL NOT NULL , EMAIL VARCHAR(30) CONSTRAINT CHKMAIL CHECK (EMAIL='%@%.%'), PAGE_FB VARCHAR(50) CONSTRAINT UNPAGE UNIQUE CONSTRAINT CHKWEB CHECK (PAGE_FB='http://%'));

CREATE TABLE  ACHATS (INTITULE VARCHAR(50), LOGIN VARCHAR(15), NBCOUPON NUMBER CONSTRAINT NNNB NOT NULL, CONSTRAINT PKIL PRIMARY KEY (INTITULE,LOGIN));

ALTER TABLE DEALS ADD CONSTRAINT FK_NOMCAT FOREIGN KEY (NOM_CATG) REFERENCES CATEGORIES (NOM_CATG);

ALTER TABLE DEALS ADD CONSTRAINT FK_NOMPREST FOREIGN KEY (NOM_PRESTATAIRE) REFERENCES PRESTATAIRES_SERVICES (NOM_PREST);

ALTER TABLE ACHATS ADD CONSTRAINT FK_INT FOREIGN KEY (INTITULE) REFERENCES DEALS (INTITULE);

ALTER TABLE ACHATS ADD CONSTRAINT FK_LOG FOREIGN KEY (LOGIN) REFERENCES MEMBRES (LOGIN);

ALTER TABLE DEALS MODIFY PRIX_I CONSTRAINT NNPRIX NOT NULL;

ALTER TABLE DEALS DROP (PRIX_D);

ALTER TABLE ACHATS ADD (DATE_ACHATS DATE);

ALTER TABLE ACHATS DROP CONSTRAINT PKIL;

ALTER TABLE ACHATS ADD CONSTRAINT PKACHATS PRIMARY KEY (INTITULE, LOGIN, DATE_ACHATS);

ALTER TABLE ACHATS ADD CONSTRAINT CHKCOUPON CHECK (NBCOUPON<=5 AND NBCOUPON>=1);




